nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']
        allow_headers: 
            [
                'Content-Type',
                'Authorization',
                'X-User-Id',
                'X-User-Name',
                'X-User-Area'
            ]
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: 
                [
                    'Content-Type',
                    'Authorization',
                    'X-User-Id',
                    'X-User-Name',
                    'X-User-Area'
                ]
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: true
